# Multiple Linear Regression

Model: $Y-\beta_{0}+\beta_{1}x_{1}+\beta_{2}x_{2}+\dotsb+\beta_{k}x_{k}+\epsilon$

$k$ = number of regressor variables
$p$ = number of parameters in the model
$p$ = k+1

We can rewrite this into Matrix form as: $y=X\beta+\epsilon$

$$
y=\begin{bmatrix}
y_{1} \\
y_{2} \\
\vdots \\
y_{n}
\end{bmatrix}\qquad X=\begin{bmatrix}
1 & x_{11} & x_{12} & x_{1k} \\
1& x_{21} & x_{22}& x_{2k} \\
\vdots  & \vdots & \ddots &  \vdots \\
1 & x_{n1} & x_{n_2} & x_{nk}  \\
\end{bmatrix} \qquad \beta=\begin{bmatrix}
\beta_{0} \\
\beta_{1} \\
\vdots \\
\beta_{k}
\end{bmatrix}\qquad \epsilon=\begin{bmatrix}
\epsilon_{1} \\
\epsilon_{2} \\
\vdots \\
\epsilon_{n}
\end{bmatrix}
$$

$y$ = Vector of our observations
$X$ = Data/Design/Model Matrix
$\beta$ = Model parameter Vector
$\epsilon$ = random errors (n is the number of observations)

Sum of Squares:

$$
L=\sum_{i=1}^n \epsilon _{i}^2=(y-X\beta)'(y-X\beta)
$$

The least squares estimator $\hat{\beta}$ is the solution for $\beta$ in the equations: $\frac{\alpha L}{\alpha\beta}=0$ this can be minimized as normal equations: $X'X\hat{\beta}=X'y$ which is the same as $[X^T\cdot X]\cdot \hat{\beta}=X^T\cdot y$

Solving the normal equations for $\hat{\beta}=(X'X)^{-1}X'y$ which is the regression coefficient in our model. It is the same as $\hat{\beta}=[X^T\cdot X]^{-1}\cdot X^T\cdot y$

This Matrix Equation provides the values of the model parameters that minimize $L$ (Least Squares).


In [127]:
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as pl

mat_X = np.flipud(
    np.rot90(np.array([[1, 1, 1, 1, 1], [-7, -3, 1, 5, 9], [8, 4, -2, -6, -10]]))
)  # 5x3 Matrix, daten/data
vec_y = np.array([-210, -90, 60, 150, 270]).reshape(
    -1, 1
)  # 5x1 vector of our observation
mat_A = mat_X.T.dot(mat_X)  # Mat A = X^T*X
vec_b = mat_X.T.dot(vec_y)  # Vec X^T * y
vec_c = la.inv(mat_A).dot(vec_b)  # Model Parameter Vector
vec_e = vec_y - mat_X.dot(vec_c)  # Error Vector


print(f"#" * 30)
print(f"\nDatenmatrix X:")
print(mat_X)
print(f"\n")
print(f"#" * 30)
print(f"\n")


print(f"#" * 30)
print(f"\nObservations Vektor y:")
print(vec_y)
print(f"\n")
print(f"#" * 30)
print(f"\n")


print(f"#" * 30)
print(f"\nBerechne A = X^T*X:")

print(f"\nX^T=\n{mat_X.T}")
print(f"\nX=\n{mat_X}")

print(f"\n\Zwischenschritt:\n todo")

print(f"\nResultat:")
print(f"\nA=\n{mat_A}")
print(f"#" * 30)
print(f"\n")

print(f"#" * 30)
print(f"\nBerechne b = X^T*y:")
print(f"\nX^T=\n{mat_X.T}")
print(f"\ny=\n{vec_y}")

print(f"\n\Zwischenschritt:\n {mat_X.T * vec_y.T}")

print(f"\nResultat:")
print(f"\nb=\n{vec_b}")
print(f"#" * 30)
print(f"\n")

print(f"#" * 30)
print(f"\nBerechne c = A^-1 * b:")
print(f"\nA^-1=\n{(mat_A)}^-1")
print(f"\nb=\n{vec_b}")
print(f"\nResultat:")
print(f"\nc=\n{vec_c}")
print(f"\n")
print(f"#" * 30)
print(f"\n")


print(f"#" * 30)
print(f"\nBerechne e = y-Xc:")
print(f"\ny=\n{vec_y}")
print(f"\n\Zwischenschritt multiplikation Xc:\n {mat_X * vec_c.T}")
print(f"\n\Zwischenschritt summe Xc:\n {np.matrix(np.sum(mat_X * vec_c.T,axis=1)).T}")
print(f"\nResultat:")
print(vec_e)
print(f"\n")
print(f"#" * 30)
print(f"\n")

##############################

Datenmatrix X:
[[  1  -7   8]
 [  1  -3   4]
 [  1   1  -2]
 [  1   5  -6]
 [  1   9 -10]]


##############################


##############################

Observations Vektor y:
[[-210]
 [ -90]
 [  60]
 [ 150]
 [ 270]]


##############################


##############################

Berechne A = X^T*X:

X^T=
[[  1   1   1   1   1]
 [ -7  -3   1   5   9]
 [  8   4  -2  -6 -10]]

X=
[[  1  -7   8]
 [  1  -3   4]
 [  1   1  -2]
 [  1   5  -6]
 [  1   9 -10]]

\Zwischenschritt:
 todo

Resultat:

A=
[[   5    5   -6]
 [   5  165 -190]
 [  -6 -190  220]]
##############################


##############################

Berechne b = X^T*y:

X^T=
[[  1   1   1   1   1]
 [ -7  -3   1   5   9]
 [  8   4  -2  -6 -10]]

y=
[[-210]
 [ -90]
 [  60]
 [ 150]
 [ 270]]

\Zwischenschritt:
 [[ -210   -90    60   150   270]
 [ 1470   270    60   750  2430]
 [-1680  -360  -120  -900 -2700]]

Resultat:

b=
[[  180]
 [ 4980]
 [-5760]]
##############################


######

In [143]:
import numpy as np
import numpy.linalg as la

X = np.array([[1, 1, 1, 1], [1, 2, 2, 1], [1, 1, 2, 2]]).T

y = np.array([[1, 2, 3, 3]]).T

X_T_X = X.T.dot(X)
print(X_T_X)
print(la.det(X_T_X))

[[ 4  6  6]
 [ 6 10  9]
 [ 6  9 10]]
3.9999999999999964


In [201]:
# input is an unsorted list of 3 positive integers
def pythagorean_triple(integers):
    for i, v in enumerate(integers):
        integers[i] = integers[i] ** 2
    if (
        integers[0] + integers[1] == integers[2]
        or integers[1] + integers[2] == integers[0]
        or integers[0] + integers[2] == integers[1]
    ):
        return True
    else:
        return False
    pass


integers = [5, 4, 3]
pythagorean_triple(integers)

[25, 16, 9]


True