In [1]:
import numpy as np
import numpy.linalg as la
import pprint
import scipy
import scipy.linalg
import matplotlib.pyplot as plt
import matplotlib

# Vector Laws

1. $\quad \mathbf{a}+\mathbf{b}=\mathbf{b}+\mathbf{a} \quad$ Kommutativgesetz
2. $\quad \mathbf{a}+(\mathbf{b}+\mathbf{c})=(\mathbf{a}+\mathbf{b})+\mathbf{c} \quad$ Assoziativgesetz
3. $\quad \mathbf{a}+\mathbf{0}=\mathbf{a} \quad$ Existenz eines Neutralelements 0
4. $\quad \mathbf{a}+(-\mathbf{a})=\mathbf{0} \quad$ Existenz des Inversen -a von a
5. $\quad \lambda(\mathbf{a}+\mathbf{b})=\lambda \mathbf{a}+\lambda \mathbf{b}$
6. $\quad(\lambda+\mu) \mathbf{a}=\lambda \mathbf{a}+\mu \mathbf{a}$
7. $\quad(\lambda \mu) \mathbf{a}=\lambda(\mu \mathbf{a})=\mu(\lambda \mathbf{a})$
8. $\quad1 a=a$


# Intersection of two Lines

If the tip of the vector $p$ points to a point on the line $g$, and the line runs in the direction of the vector $u$, then the equation $g:r=p+λu$ generates all points of the line, as $\lambda$ runs through all real numbers.

#### Definition

$$
g:r=\begin{pmatrix}
pg_{1} \\
pg_{2}
\end{pmatrix}+\lambda \begin{pmatrix}
ug_{1} \\
ug_{2} \\
\end{pmatrix}
\quad
h:r=\begin{pmatrix}
ph_{1} \\
ph_{2} \\
\end{pmatrix}+\upsilon \begin{pmatrix}
uh_{1} \\
uh_{2}
\end{pmatrix} \Rrightarrow
\begin{pmatrix}
pg_{1} \\
pg_{2}
\end{pmatrix}+\lambda \begin{pmatrix}
ug_{1} \\
ug_{2} \\
\end{pmatrix}
=
\begin{pmatrix}
ph_{1} \\
ph_{2} \\
\end{pmatrix}+\upsilon \begin{pmatrix}
uh_{1} \\
uh_{2}
\end{pmatrix}
$$

Which gives us a system of equations to solve:

$$
\begin{align}
pg_{1}-\lambda ug_{1}=ph_{1}+\upsilon uh_{1}  \\
pg_{2}-\lambda ug_{2}=ph_{2}+\upsilon uh_{2}
\end{align}
$$

#### Example

$$
g:r=\begin{pmatrix}
-3 \\
2
\end{pmatrix}+\lambda \begin{pmatrix}
2 \\
2 \\
\end{pmatrix}
\quad
h:r=\begin{pmatrix}
4 \\
3 \\
\end{pmatrix}+\upsilon \begin{pmatrix}
1 \\
-2
\end{pmatrix} \Rrightarrow
\begin{pmatrix}
-3 \\
2
\end{pmatrix}+\lambda \begin{pmatrix}
2 \\
2 \\
\end{pmatrix}
=
\begin{pmatrix}
4 \\
3 \\
\end{pmatrix}+\upsilon \begin{pmatrix}
1 \\
-2
\end{pmatrix}
$$

turns into following equations:

$$
\begin{align}
-3+2\lambda=4+1\upsilon  & \Rrightarrow  & -3+2\lambda=4+1\upsilon & \Rrightarrow & -5=1+3\upsilon \Rrightarrow -6=3\upsilon \Rrightarrow-2=\upsilon\\
2+2\lambda=3-2\upsilon &   & -2-2\lambda=-3+2\upsilon
\end{align}
$$

put $\upsilon=-2$ into any equation and you will get $\lambda=\frac{5}{2}$ if everything adds up it is correct.

Now you can add either value into one of the line equation to get the point where the intersection is. I will use $\upsilon=-2$.

$$
4+(-2)=2 \quad 3-(-4)=7 \quad \Rrightarrow \begin{pmatrix}
2 \\
7
\end{pmatrix}
$$


## With Numpy

In NumPy it is very easy to solve linear equations. We need to rearrange the equations into the coefficient matrix and the constant matrix.

The coefficient matrix is the left term of the equation

$$
\begin{align}
-3+2\lambda=4+1\upsilon  & \Rrightarrow  & 2\lambda-1\upsilon=4+3 & \Rrightarrow & 2, -1 \\
2+2\lambda=3-2\upsilon &   & 2\lambda+2\upsilon=3-2 & \Rrightarrow & 2,2
\end{align}
$$

The constant matrix $b$ is simply the right term of the equation

$$
\begin{align}
-3+2\lambda=4+1\upsilon  & \Rrightarrow  & 2\lambda-1\upsilon=4+3 & \Rrightarrow & 7 \\
2+2\lambda=3-2\upsilon &   & 2\lambda+2\upsilon=3-2 & \Rrightarrow & 1
\end{align}
$$

This results in

$$
Ax = b \qquad \Rrightarrow \begin{bmatrix}
2 & -1 \\
2 & 2
\end{bmatrix}=\begin{pmatrix}
7 \\
1
\end{pmatrix}
$$


In [2]:
A = np.array([[2, -1], [2, 2]])
b = np.array([[7], [1]])

la.solve(A, b)

array([[ 2.5],
       [-2. ]])

In [3]:
# Substitute in previous equation

np.array([[-3, 2]]) + la.solve(A, b)[0] * np.array([2, 2])

array([[2., 7.]])

# Gaussian Elimination


In [4]:
def RowSwap(A, k, l):
    # =============================================================================
    #     A is a NumPy array.  RowSwap will return duplicate array with rows
    #     k and l swapped.
    # =============================================================================
    print(f"\nSwap R{k+1} and R{l+1}")
    k -= 1
    l -= 1
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype("float64")

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
    print(f"{B}")
    return B


def RowScale(A, k, scale):
    # =============================================================================
    #     A is a NumPy array.  RowScale will return duplicate array with the
    #     entries of row k multiplied by scale.
    # =============================================================================
    print(f"\nR{k} = R{k} * {str(scale)}")
    k -= 1
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype("float64")

    for j in range(n):
        B[k][j] *= scale
    print(f"{B}")
    return B


def RowAdd(A, k, l, scale):
    # =============================================================================
    #     A is a numpy array.  RowAdd will return duplicate array with row
    #     l modifed.  The new values will be the old values of row l added to
    #     the values of row k, multiplied by scale.
    # =============================================================================
    print(f"\nR{l} = R{l} + {str(scale)}R{k}    ")
    k -= 1
    l -= 1
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype("float64")

    for j in range(n):
        B[l][j] += B[k][j] * scale
    print(f"{B}")
    return B


A = np.array([[1, -1, 1, 3], [2, 1, 8, 18], [4, 2, -3, -2]])
print(A)

A = RowAdd(A, 1, 2, -2)


A = RowAdd(A, 1, 3, -4)


A = RowScale(A, 2, 1 / 3)


A = RowAdd(A, 2, 3, -6)


A = RowScale(A, 3, -1 / 19)

[[ 1 -1  1  3]
 [ 2  1  8 18]
 [ 4  2 -3 -2]]

R2 = R2 + -2R1    
[[ 1. -1.  1.  3.]
 [ 0.  3.  6. 12.]
 [ 4.  2. -3. -2.]]

R3 = R3 + -4R1    
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   6.  -7. -14.]]

R2 = R2 * 0.3333333333333333
[[  1.  -1.   1.   3.]
 [  0.   1.   2.   4.]
 [  0.   6.  -7. -14.]]

R3 = R3 + -6R2    
[[  1.  -1.   1.   3.]
 [  0.   1.   2.   4.]
 [  0.   0. -19. -38.]]

R3 = R3 * -0.05263157894736842
[[ 1. -1.  1.  3.]
 [ 0.  1.  2.  4.]
 [-0. -0.  1.  2.]]


## Gauss Jordan


In [5]:
A = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
AI = la.inv(A)
print(f"Inverse:\n{AI}")
print(f"\nStart Matrix: \n{A}")
A = np.append(A, np.eye(3), axis=1)
print(f"\n Extend the Matrix with the Identity Matrix\n{A}")


A = RowAdd(A, 1, 3, -5)
A = RowAdd(A, 2, 3, 4)
A = RowAdd(A, 3, 2, -4)
A = RowAdd(A, 3, 1, -3)
A = RowAdd(A, 2, 1, -2)
print(f"Inverse:\n{AI}")

Inverse:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

Start Matrix: 
[[1 2 3]
 [0 1 4]
 [5 6 0]]

 Extend the Matrix with the Identity Matrix
[[1. 2. 3. 1. 0. 0.]
 [0. 1. 4. 0. 1. 0.]
 [5. 6. 0. 0. 0. 1.]]

R3 = R3 + -5R1    
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]

R3 = R3 + 4R2    
[[ 1.  2.  3.  1.  0.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]

R2 = R2 + -4R3    
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]

R1 = R1 + -3R3    
[[  1.   2.   0.  16. -12.  -3.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]

R1 = R1 + -2R2    
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]
Inverse:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


# LU Zerlegung


In [6]:
A = np.array([[1, 2, 1], [2, 1, 0], [-3, 0, 9]])
A

array([[ 1,  2,  1],
       [ 2,  1,  0],
       [-3,  0,  9]])

In [7]:
# 3x3 Einheitsmatrix
E = np.eye(3, 3)

# manipuliere das gewünschte element in das richtige
E21 = E.copy()
E21[1, 0] = -2

E21 @ A

array([[ 1.,  2.,  1.],
       [ 0., -3., -2.],
       [-3.,  0.,  9.]])

In [8]:
E31 = E.copy()
E31[2, 0] = 3

print(E31)

E31 @ E21 @ A

[[1. 0. 0.]
 [0. 1. 0.]
 [3. 0. 1.]]


array([[ 1.,  2.,  1.],
       [ 0., -3., -2.],
       [ 0.,  6., 12.]])

In [9]:
E32 = E.copy()
E32[2, 1] = 2

print(E32)

E32 @ E31 @ E21 @ A

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 1.]]


array([[ 1.,  2.,  1.],
       [ 0., -3., -2.],
       [ 0.,  0.,  8.]])

In [10]:
U = E32 @ E31 @ E21 @ A

In [11]:
L = la.inv(E21) @ la.inv(E31) @ la.inv(E32)

In [12]:
L @ U

array([[ 1.,  2.,  1.],
       [ 2.,  1.,  0.],
       [-3.,  0.,  9.]])

In [13]:
A - L @ U

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## LU Decomposition Function


In [14]:
def LU(A):
    n = A.shape[0]
    L = np.eye(n)
    U = np.copy(A)

    for i in range(n - 1):
        L[i + 1 : n, i] = U[i + 1 : n, i] / U[i, i]
        for k in range(i + 1, n):
            U[k, i:n] = U[k, i:n] - (L[k, i] * U[i, i:n])

    return (L, U)


def EliminationMatix(A, E, r1, r2):
    E = np.eye(A.shape[0])  # Identity Matrix based on A size
    Ex = E.copy()
    print(f"\nE{r1}{r2} factor:  ")
    x = input()
    print(x)
    Ex[r1 - 1, r2 - 1] = x
    print(f"\nE{r1}{r2} =\n")
    print(Ex)
    return Ex


def LUSteps(A):
    # A is the input Matrix
    # Ex Elimination Matrixes
    # *args Elimination Matrixes as arguments
    print(f"A = \n{A}")
    E21 = EliminationMatix(A, E, 2, 1)
    E31 = EliminationMatix(A, E, 3, 1)
    E32 = EliminationMatix(A, E, 3, 2)
    print(f"\nL=\n")
    print(la.inv(E21) @ la.inv(E31) @ la.inv(E32))
    print(f"\nU =\n")
    print(E32 @ E31 @ E21 @ A)
    print(f"\nLU=\n")
    print(L @ U)
    print(f"\nCheck A - L@U =\n")
    print(A - L @ U)

    return L, U

In [15]:
LUSteps(A)

A = 
[[ 1  2  1]
 [ 2  1  0]
 [-3  0  9]]

E21 factor:  



ValueError: could not convert string to float: ''

## Solving a system of linear equation with LU-Decomposition

The original system of linear equation $Ax = b$ can be simplified with LU-decomposition:

$$
\begin{align}
Ax=b \\
A=LU \\
LUx=b
\end{align}
$$

Now we define:

$$
\begin{align}
Ly=b \\
Ux=y
\end{align}
$$

### Example

$$
\begin{align}
u+2v=5 \\
4u+9v=21
\end{align}
$$

Converted to matrixes

$$
A=\begin{pmatrix}
1 & 2 \\
4 & 9
\end{pmatrix}\cdot \begin{pmatrix}
u \\
v
\end{pmatrix}=\begin{pmatrix}
5 \\
21
\end{pmatrix}
$$

After LU Decomposition we get:

$$
\begin{pmatrix}
1 & 2 \\
4 & 9
\end{pmatrix}=\begin{pmatrix}
1 & 0 \\
4  & 1
\end{pmatrix}\cdot \begin{pmatrix}
1 & 2 \\
0 & 1
\end{pmatrix}
$$


In [ ]:
A = np.array([[1, 2], [4, 9]])

b = np.array([[5], [21]])
L, U = LU(A)

print(L)
print(U)

[[1. 0.]
 [4. 1.]]
[[1 2]
 [0 1]]


In [ ]:
y = la.solve(L, b)
print(y)

[[5.]
 [1.]]


In [ ]:
x = la.solve(U, y)
print(x)

[[3.]
 [1.]]


In [ ]:
A @ x - b

array([[0.],
       [0.]])

In [ ]:
A = np.array([[1, -1, 3], [2, 4, 3], [4, 8, 4]])


# L,U = LUSteps(A)

print(L)
print(U)
b = np.array([[-1], [1], [8]])

y = la.solve(L, b)
print(y)
x = la.solve(U, y)

print(A @ x - b)

[[1. 0. 0.]
 [2. 1. 0.]
 [4. 2. 1.]]
[[ 1. -1.  3.]
 [ 0.  6. -3.]
 [ 0.  0. -2.]]
[[-1.]
 [ 3.]
 [ 6.]]
[[0.]
 [0.]
 [0.]]
-12.0
